name: Deploy to VPS
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: Deploy to VPS
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          concurrency: 4
          remote: ${{ secrets.VPS_REMOTE_PATH }}
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
