name: Deploy to Raspberry Pi
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install and Build
      run: npm install && npm run build
      
    - name: Deploy via SCP
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        local: dist 
        remote: ${{ secrets.REMOTE_PATH }}
        host: ${{ secrets.HOST }} 
        port: ${{ secrets.PORT }} 
        user: ${{ secrets.USER }} 
        key: ${{ secrets.KEY }}
